apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: emailservice
  name: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: emailservice
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: emailservice
    spec:
      containers:
        - image: artifactory.obi.ninja/cymbal-shops/emailservice:v7
          name: emailservice
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
