apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: loadgenerator
  name: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: loadgenerator
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: loadgenerator
    spec:
      containers:
        - env:
            - name: AD_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  key: AD_SERVICE_ADDR
                  name: svc-addresses-env
            - name: CART_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  key: CART_SERVICE_ADDR
                  name: svc-addresses-env
            - name: CHECKOUT_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  key: CHECKOUT_SERVICE_ADDR
                  name: svc-addresses-env
            - name: CURRENCY_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  key: CURRENCY_SERVICE_ADDR
                  name: svc-addresses-env
            - name: EMAIL_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  key: EMAIL_SERVICE_ADDR
                  name: svc-addresses-env
            - name: FRONTEND_ADDR
              valueFrom:
                configMapKeyRef:
                  key: FRONTEND_ADDR
                  name: svc-addresses-env
            - name: PAYMENT_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  key: PAYMENT_SERVICE_ADDR
                  name: svc-addresses-env
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  key: PRODUCT_CATALOG_SERVICE_ADDR
                  name: svc-addresses-env
            - name: RECOMMENDATION_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  key: RECOMMENDATION_SERVICE_ADDR
                  name: svc-addresses-env
            - name: SHIPPING_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  key: SHIPPING_SERVICE_ADDR
                  name: svc-addresses-env
            - name: SHOPPING_ASSISTANT_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  key: SHOPPING_ASSISTANT_SERVICE_ADDR
                  name: svc-addresses-env
          image: obimadu/loadgenerator
          name: loadgenerator
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
