pipeline {
    agent {
        label 'ubuntu'
    }

    environment {
        DOCKER_IMAGE_NAME = "checkoutservice"
        JFROG_CR_USERNAME = "cymbal-shops"
        JFROG_CR_IMAGE = "${JFROG_CR_USERNAME}/${DOCKER_IMAGE_NAME}"
        SONARQUBE_PROJECT_ID = "cymbal-checkoutservice"
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                dir('src/checkoutservice') {
                    withSonarQubeEnv(installationName: 'SonarQube', credentialsId: 'sonarqube-token-90') {
                        script {
                            def scannerHome = tool 'SonarQubeScanner'
                            sh "${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=${SONARQUBE_PROJECT_ID}"
                        }
                    }
                }
            }
        }

        stage("Code Quality Gate") {
            steps {
                waitForQualityGate abortPipeline: true
            }
        }

        stage('Build and Tag Image') {
            steps {
                dir('src/checkoutservice') {
                    script {
                        // Built and Tag Image with Current Build No.
                        dockerImage = docker.build("${JFROG_CR_IMAGE}:v${currentBuild.number}")
                    }
                }
            }
        }

        stage('Scan with Trivy') {
            environment {
                TRIVY_DB_REPOSITORY = "public.ecr.aws/aquasecurity/trivy-db"
                TRIVY_JAVA_DB_REPOSITORY = "public.ecr.aws/aquasecurity/trivy-java-db"
            }
            steps {
                script {
                    sh "trivy image --severity HIGH,CRITICAL ${JFROG_CR_IMAGE}:v${currentBuild.number}"
                }
            }
        }

        stage('Push Image to Jfrog CR') {
            steps {
                script {
                    docker.withRegistry('https://artifactory.obi.ninja', 'jfrog-cymbal-shops') {
                        docker.image("${JFROG_CR_IMAGE}:v${currentBuild.number}").push()
                        docker.image("${JFROG_CR_IMAGE}:v${currentBuild.number}").push("latest")
                    }
                }
            }
        }
    }
}
