pipeline {
    agent {
        label "ubuntu"
      }

    environment {
        DOCKER_HUB_CREDENTIALS = credentials('cymbal-shops-docker-hub-credentials')
        DOCKER_IMAGE_NAME = "adservice"
        DOCKER_IMAGE_TAG = "latest"
        DOCKER_IMAGE = "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Tag Docker Image') {
            steps {
                dir('src/adservice') {
                    script {
                        dockerImage = docker.build("${DOCKER_IMAGE}")
                    }
                }
            }
        }

        stage('Scan with Trivy') {
            steps {
                script {
                    sh "trivy image --severity HIGH,CRITICAL ${DOCKER_IMAGE}"
                }
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'cymbal-shops-docker-hub-credentials') {
                        dockerImage.push()
                    }
                }
            }
        }
    }
}

